### ISSUE TITLE
Support for disabling touchscreen+touchpad(+nipple) when laptop lid is closed

### ISSUE THREAD

**Issue by b1tt1** [wdbm/spin#10]
Hi,

I'm a really happy user of spin.py, it has made using my Thinkpad Yoga 20CD much nicer.

But I have one request: Some Yoga's have a notorious (hardware) bug which causes them to emit spurious touch events (probably from touchscreen) when the laptop lid is closed (i.e., when connected to an external monitor+keyboard+mouse). I'm suffering from these from time to time, and they can be very irritating (especially since they produce a mouse click in addition to moving the mouse cursor).

Would it be possible to add a third mode to spin.py ("lid closed" mode or similar), which could then disable touchscreen and touchpad (and possible nipple, since that cannot be used either)? (Detecting when the lid is closed should be fairly trivial, I suppose.)

Regards,
Matti Rintala

**Comment by igalic** [comment]
```
igalic@sinix ~> acpi_listen
button/lid LID close
button/lid LID open
```
