### ISSUE TITLE
Python >2 required

### ISSUE THREAD

**Issue by jbrepogmailcom** [wdbm/spin#16]
But I have Python 2.7 installed. What now please?

**Comment by freiheitsnetz** [comment]
I experience the same problem. Followed the simple instructions in the readme, but it does not work. Has it something to do with the case that the package python-qt5 does not exist with Ubuntu 18.04? There only python-pyqt5 is available

**Comment by wdbm** [comment]
Hey @freiheitsnetz, I've updated the documentation to include suggested setup instructions for Ubuntu 16.04 LTS and for Ubuntu 18.04 LTS. Hopefully that works. Feel free to report if it does not!

**Comment by freiheitsnetz** [comment]
Thanks for the quick reply. I tried it and found that the development packages are not needed. On the other hand `pip3` has to be used. I updated the Readme according to my working instructions in a fork and will create a pull request.

**Comment by wdbm** [comment]
Thanks for getting back to me. I think it's reasonable to assume Python 3 as the default now because Python 2 is set to be supported only for another 8 months or so.
