### ISSUE TITLE
Finding events on Thinkpad Yoga 14?

### ISSUE THREAD

**Issue by andrew-w-sherman** [wdbm/spin#7]
Hi,
Don't mean to be a bother, but I have the recently released thinkpad yoga 14, and it's not working properly with the script as is -- which is to be expected, since the hardware is changed and certain events will work differently. I'm trying to see if I can modify it myself to do the listening, so I've been poking around. I ran acpi_listen and moved the hinge through its full range, and no events popped up. I'm wondering if, since you found the original socket, you had any insights for how to locate the socket -- or whatever it is -- that these events are coming through. If it can be found I would be happy to contribute its location to perhaps expand the compatibility scope of the project. For context, I'm running Ubuntu 14.10 and I believe all my drivers and such are fully updated.
An ominous side note -- from some of the research I've done so far it seems possible that these events would only be accessible through the accelerometer, which would be a bit of an issue, as everything I've done to test js0/event7 -- supposedly where the accelerometer is located -- have been met with "operation not permitted" messages and such.
Thanks,
Andrew

**Comment by wdbm** [comment]
Hey there! Thanks for raising this issue. Some of the pressure from the LHC restart is off now and I've got my hands now on a second generation ThinkPad Yoga 12, so I've had a chance to consider this.

# ThinkPad Yoga 14

Regarding hardware difficulties with the ThinkPad Yoga 14, could you try the current version of spin? Let's see how well it works. If you have a moment, it could be of assistance if you report on the output you get for the following command:

```Bash
xinput --list --id-only | xargs xinput --list-props
```

# acceleration

It appears that acceleration information is accessible via the IIO interface. As a rough test, the following code should print a vector that corresponds roughly to the acceleration of the device in three directions:

```Bash
#!/usr/bin/env python

import time
import os
import glob

def main():

    acceleration = accelerationVector()

    while True:
        print(acceleration)
        time.sleep(0.1)

class accelerationVector(list):

    def __init__(self):
        list.__init__(self)  
        # Access the IIO interface to the accelerometer.
        devicesDirectories = glob.glob("/sys/bus/iio/devices/iio:device*")
        for directory in devicesDirectories:
            if "accel_3d" in open(os.path.join(directory, "name")).read():
                self.accelerometerDirectory = directory
        self.accelerometerScaleFileFullPath =\
            self.accelerometerDirectory + "/" + "in_accel_scale"
        self.accelerometerAxisxFileFullPath =\
            self.accelerometerDirectory + "/" + "in_accel_x_raw"
        self.accelerometerAxisyFileFullPath =\
            self.accelerometerDirectory + "/" + "in_accel_y_raw"
        self.accelerometerAxiszFileFullPath =\
            self.accelerometerDirectory + "/" + "in_accel_z_raw"
        self.accelerometerScaleFile = open(self.accelerometerScaleFileFullPath)
        self.accelerometerAxisxFile = open(self.accelerometerAxisxFileFullPath)
        self.accelerometerAxisyFile = open(self.accelerometerAxisyFileFullPath)
        self.accelerometerAxiszFile = open(self.accelerometerAxiszFileFullPath)
        # Access the scale.
        self.scale = float(self.accelerometerScaleFile.read())
        # Initialise the vector.
        self.extend([0, 0, 0])
        self.update()

    def update(self):
        # Access the acceleration.
        self.accelerometerAxisxFile.seek(0)
        self.accelerometerAxisyFile.seek(0)
        self.accelerometerAxiszFile.seek(0)
        acceleration_x = float(self.accelerometerAxisxFile.read()) * self.scale
        acceleration_y = float(self.accelerometerAxisyFile.read()) * self.scale
        acceleration_z = float(self.accelerometerAxiszFile.read()) * self.scale
        # Update the vector.
        self[0] = acceleration_x
        self[1] = acceleration_y
        self[2] = acceleration_z

    def __repr__(self):
        self.update()
        return(list.__repr__(self))

if __name__ == "__main__":
    main()
```

Maybe this is a passable way to approach the problem. I have yet to consider the orientations of the device that should correspond to the various modes and how to assess the 'stability' of that acceleration vector. Let me know if you have any thoughts.

**Comment by andrew-w-sherman** [comment]
Below is the output from the xinput command, though it doesn't seem too helpful. From prior experience I believe I remember the accelerometer being oddly mapped, I think to /dev/input/js0, but not sure. Running the accelerometer test correctly displays the orientation vector for the screen, which is in iio:device0. I assume to properly assess the mode that needs to be entered, you would need two accelerometer readings, one from the screen and one from the body. So far all the streams I've tested in iio/devices/iio:device\* are either not orientation dependent (as far as I can tell) or they are only dependent on the orientation of the screen. The vectors look relatively stable, the highest variance I see when left on a flat surface is about +-0.1 or 0.2. Could maybe benefit from some processing but I'm not sure. Thanks for getting back to me!

    Device 'Virtual core pointer':
    	Device Enabled (139):	1
    	Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
    Device 'Virtual core XTEST pointer':
	    Device Enabled (139):	1
	    Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	    XTEST Device (256):	1
    Device 'SynPS/2 Synaptics TouchPad':
	    Device Enabled (139):	1
	    Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	    Device Accel Profile (268):	1
	    Device Accel Constant Deceleration (269):	2.500000
	    Device Accel Adaptive Deceleration (270):	1.000000
	    Device Accel Velocity Scaling (271):	12.500000
	    Synaptics Edges (293):	1766, 5380, 1637, 4455
	    Synaptics Finger (294):	25, 30, 0
	    Synaptics Tap Time (295):	180
	    Synaptics Tap Move (296):	234
	    Synaptics Tap Durations (297):	180, 180, 100
	    Synaptics ClickPad (298):	1
	    Synaptics Middle Button Timeout (299):	0
	    Synaptics Two-Finger Pressure (300):	282
	    Synaptics Two-Finger Width (301):	7
	    Synaptics Scrolling Distance (302):	106, 106
	    Synaptics Edge Scrolling (303):	0, 0, 0
	    Synaptics Two-Finger Scrolling (304):	1, 0
	    Synaptics Move Speed (305):	1.000000, 1.750000, 0.037538, 0.000000
	    Synaptics Off (306):	0
	    Synaptics Locked Drags (307):	0
	    Synaptics Locked Drags Timeout (308):	5000
	    Synaptics Tap Action (309):	0, 0, 0, 0, 0, 2, 3
	    Synaptics Click Action (310):	1, 3, 2
	    Synaptics Circular Scrolling (311):	0
	    Synaptics Circular Scrolling Distance (312):	0.100000
	    Synaptics Circular Scrolling Trigger (313):	0
	    Synaptics Circular Pad (314):	0
	    Synaptics Palm Detection (315):	1
	    Synaptics Palm Dimensions (316):	10, 200
	    Synaptics Coasting Speed (317):	20.000000, 50.000000
	    Synaptics Pressure Motion (318):	30, 160
	    Synaptics Pressure Motion Factor (319):	1.000000, 1.000000
	    Synaptics Grab Event Device (320):	0
	    Synaptics Gestures (321):	1
	    Synaptics Capabilities (322):	1, 0, 0, 1, 1, 1, 1
	    Synaptics Pad Resolution (323):	52, 45
	    Synaptics Area (324):	0, 0, 0, 0
	    Synaptics Soft Button Areas (325):	3573, 0, 4094, 0, 0, 0, 0, 0
	    Synaptics Secondary Soft Button Areas (326):	3909, 0, 0, 1899, 3236, 3909, 0, 1899
	    Synaptics Noise Cancellation (327):	26, 26
	    Device Product ID (260):	2, 7
	    Device Node (261):	"/dev/input/event6"
    Device 'TPPS/2 IBM TrackPoint':
	    Device Enabled (139):	1
	    Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	    Device Accel Profile (268):	0
	    Device Accel Constant Deceleration (269):	1.000000
	    Device Accel Adaptive Deceleration (270):	1.000000
	    Device Accel Velocity Scaling (271):	10.000000
	    Device Product ID (260):	2, 10
	    Device Node (261):	"/dev/input/event20"
	    Evdev Axis Inversion (272):	0, 0
	    Evdev Axes Swap (274):	0
	    Axis Labels (275):	"Rel X" (149), "Rel Y" (150)
	    Button Labels (276):	"Button Left" (142), "Button Middle" (143), "Button Right" (144), "Button Wheel Up" (145), "Button Wheel Down" (146)
	    Evdev Scrolling Distance (277):	0, 0, 0
	    Evdev Middle Button Emulation (278):	0
	    Evdev Middle Button Timeout (279):	50
	    Evdev Third Button Emulation (280):	0
	    Evdev Third Button Emulation Timeout (281):	1000
	    Evdev Third Button Emulation Button (282):	3
	    Evdev Third Button Emulation Threshold (283):	20
	    Evdev Wheel Emulation (284):	0
	    Evdev Wheel Emulation Axes (285):	0, 0, 4, 5
	    Evdev Wheel Emulation Inertia (286):	10
	    Evdev Wheel Emulation Timeout (287):	200
	    Evdev Wheel Emulation Button (288):	4
	    Evdev Drag Lock Buttons (289):	0
    Device 'SYNAPTICS Synaptics Touch Digitizer V04':
	    Device Enabled (139):	1
	    Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	    Device Accel Profile (268):	0
	    Device Accel Constant Deceleration (269):	1.000000
	    Device Accel Adaptive Deceleration (270):	1.000000
	    Device Accel Velocity Scaling (271):	10.000000
	    Device Product ID (260):	1739, 30184
	    Device Node (261):	"/dev/input/event1"
	    Evdev Axis Inversion (272):	0, 0
	    Evdev Axis Calibration (273):	<no items>
	    Evdev Axes Swap (274):	0
	    Axis Labels (275):	"Abs MT Position X" (266), "Abs MT Position Y" (267), "None" (0), "None" (0)
	    Button Labels (276):	"Button Unknown" (263), "Button Unknown" (263), "Button Unknown" (263), "Button Wheel Up" (145), "Button Wheel Down" (146)
	    Evdev Scrolling Distance (277):	0, 0, 0
	    Evdev Middle Button Emulation (278):	0
	    Evdev Middle Button Timeout (279):	50
	    Evdev Third Button Emulation (280):	0
	    Evdev Third Button Emulation Timeout (281):	1000
	    Evdev Third Button Emulation Button (282):	3
	    Evdev Third Button Emulation Threshold (283):	20
	    Evdev Wheel Emulation (284):	0
	    Evdev Wheel Emulation Axes (285):	0, 0, 4, 5
	    Evdev Wheel Emulation Inertia (286):	10
	    Evdev Wheel Emulation Timeout (287):	200
	    Evdev Wheel Emulation Button (288):	4
	    Evdev Drag Lock Buttons (289):	0
    Device 'Virtual core keyboard':
	    Device Enabled (139):	1
	    Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
    Device 'Virtual core XTEST keyboard':
	    Device Enabled (139):	1
	    Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	    XTEST Device (256):	1
    Device 'Power Button':
	    Device Enabled (139):	1
	    Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	    Device Product ID (260):	0, 1
	    Device Node (261):	"/dev/input/event4"
	    Virtual Device (262):	1
    Device 'Video Bus':
	    Device Enabled (139):	1
	    Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	    Device Product ID (260):	0, 6
	    Device Node (261):	"/dev/input/event8"
	    Virtual Device (262):	1
    Device 'Video Bus':
	    Device Enabled (139):	1
	    Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	    Device Product ID (260):	0, 6
	    Device Node (261):	"/dev/input/event9"
	    Virtual Device (262):	1
    Device 'Sleep Button':
	    Device Enabled (139):	1
	    Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	    Device Product ID (260):	0, 3
	    Device Node (261):	"/dev/input/event3"
	    Virtual Device (262):	1
    Device 'Integrated Camera':
	    Device Enabled (139):	1
	    Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	    Device Product ID (260):	1266, 46186
	    Device Node (261):	"/dev/input/event13"
    Device 'AT Translated Set 2 keyboard':
	    Device Enabled (139):	1
	    Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	    Device Product ID (260):	1, 1
	    Device Node (261):	"/dev/input/event0"
    Device 'ThinkPad Extra Buttons':
	    Device Enabled (139):	1
	    Coordinate Transformation Matrix (141):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	    Device Product ID (260):	6058, 20564
	    Device Node (261):	"/dev/input/event7"

**Comment by andrew-w-sherman** [comment]
Oh, and another small issue (likely upstream) is that switching straight to inverted screen from normal completely breaks something in X, such that suddenly the screen goes completely black and only the cursor displays (though the cursor is properly inverted). This is definitely upstream because it seems to happen even when done through the xrandr commands, but thought you might want to be aware of it.

**Comment by wdbm** [comment]
Thank you for that device listing, for mentioning the X blackout problem and for your observations on the acceleration vectors. Regarding the devices, as far as I can see, the only real difference between my machine and yours is that we're using the TouchPad/TrackPoint-buttons assembly slightly differently.

>small issue (likely upstream) is that switching straight to inverted screen from normal completely breaks something in X

Yes, I've seen this behaviour and slight variants of it. I do not know what is causing it. Something is screwing up X and it's likely upstream. Other people appear to have observed similar problems and the solutions are not very conclusive. I've seen some suggesting odd resolution changes as a solution.

# searching for screen rotation event signals

With regards to searching for some screen rotation signals, all I did was run ```acpid -d -l``` to try to identify the ACPI events corresponding to the screen rotation. Then, I implemented in Python a way to listen to the socket of the ACPI.

I don't know whether there are equivalent signals for the ThinkPad Yoga 14.

# acceleration control

You're right about needing information about the rotation of the display with respect to the body, but at least there is the information from the accelerometer in the display. Other information can be specified manually using the buttons in the graphical mode.

Anyway, I've added an acceleration control to spin. It's disabled by default but can be enabled using the appropriate button. Be cautious about using it; for me it tends to screw up X somehow. I've added details on it to the documentation.
